services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=cronos_user
      - POSTGRES_PASSWORD=cronos_password
      - POSTGRES_DB=cronos_db
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://cronos_user:cronos_password@db:5432/cronos_db
    depends_on:
      - db

volumes:
  postgres_data: